version: "3"

services:
  cassio-fernando-cv:
    container_name: cassio-fernando-cv
    build: .
    image: tectonic
    working_dir: "/cassio-fernando-cv"
    user: 1000:1000
    command: sh -c "
      tectonic -X compile cassio-fernando-cv.en.tex &&
      tectonic -X compile cassio-fernando-cv.pt-br.tex"
    volumes:
      - ./:/cassio-fernando-cv
    environment:
      - XDG_CONFIG_HOME=/cassio-fernando-cv/.tectonic
      - XDG_CACHE_HOME=/cassio-fernando-cv/.tectonic
